apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hyquioq1o-go
  janus-idp.io/tekton: hyquioq1o-go
  backstage.io/kubernetes-id: hyquioq1o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hyquioq1o-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
